name: TOOLBOXLAP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'  # تشغيل كل 6 ساعات

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2022  # أو windows-2025 حسب دعم GitHub

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Download and Install Playit
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64-signed.exe" -OutFile "$env:USERPROFILE\playit.exe"
        Start-Sleep -Seconds 5

    - name: Enable Remote Desktop (RDP)
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "admin@123" -Force)

    - name: Start Playit Tunnel
      env:
        PLAYIT_AUTH_KEY: ${{ secrets.PL }}
      run: |
        Start-Process -FilePath "$env:USERPROFILE\playit.exe" -ArgumentList "--secret $env:PLAYIT_AUTH_KEY" -NoNewWindow

    - name: Keep the GitHub Runner Alive
      run: |
        Start-Sleep -Seconds 21600  # 6 ساعات

    - name: Re-trigger Workflow Automatically
      if: always()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $headers = @{
          Authorization = "token $env:GITHUB_TOKEN"
        }

        $body = @{
          ref = "${{ github.ref_name }}"
        } | ConvertTo-Json

        Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ github.workflow }}.yml/dispatches" `
                          -Method Post -Headers $headers -Body $body -ContentType "application/json"
